version: '3'
services:
  test_server:
    build: .
    image: first_build_image
  articleServer:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./articleServer/:/home/node/app
    expose:
      - "8081"
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run migration
        npm start
    ports:
      - 3000:3000
    networks:
      - "chsearch"
  db:
    image: postgres
    ports:
      - 5438:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - "chsearch"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - "chsearch"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 8081:80
    networks:
      - "chsearch"
  exchangeServer:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./exchangeServer/:/home/node/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run migration
        npm start
    ports:
      - 3001:3000
    networks:
      - "chsearch"
  
  
volumes:
  postgres-data:
networks:
  chsearch: